name: DestroyBlock
version: 1.0.1
main: me.pljr.destroyblock.DestroyBlock
load: POSTWORLD
api-version: 1.13
authors: [9hx]
depend: [CMI]
softdepend: [Multiverse-Core]
description: Literally just destroy the block.
